version: '3.1'

services:

    openkm:
        build: .
        environment:
            - "JAVA_OPTS=-Djdbc.url=jdbc:postgresql://10.6.33.17:5432/OpenKM"
        ports:
            - 8080:8080
            - 2002:2002    
volumes:
    openkm_vol: {}
        
